services:
  - type: web
    name: amr-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py createadmin && gunicorn amr_app.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "amr-backend.onrender.com"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_IL4DJwixCb7f@ep-old-glitter-adara3gi-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: DJANGO_ADMIN_USERNAME
        value: "adminuser"
      - key: DJANGO_ADMIN_PASSWORD
        value: "AdminPass123"
      - key: DJANGO_ADMIN_EMAIL
        value: "admin@example.com"
